is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.downstreamError
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
  - errors.accountingPeriod18MonthsMax
  - errors.agentNameCharactersError
  - errors.agentNameLengthError
  - errors.agentNameNotSuppliedError
  - errors.agentNameSuppliedError
  - errors.allocatedReactivationsCannotBeNegative
  - errors.allocatedReactivationsDecimalError
  - errors.allocatedRestrictionDateBeforePrevious
  - errors.allocatedRestrictionDecimalError
  - errors.allocatedRestrictionLaterPeriodSupplied
  - errors.allocatedRestrictionNegative
  - errors.allocatedRestrictionNotSupplied
  - errors.allocatedRestrictionSupplied
  - errors.allocatedRestrictionTotalDecimalError
  - errors.allocatedRestrictionTotalDoesNotMatch
  - errors.allocatedRestrictionTotalNegative
  - errors.allocatedRestrictionTotalNotSupplied
  - errors.angieDecimalError
  - errors.ap1NotAfterGroupStartDate
  - errors.ap3BeforeGroupEndDate
  - errors.companyNameCharactersError
  - errors.companyNameLengthError
  - errors.consolidatedPartnershipsEmpty
  - errors.consolidatedPartnershipsNotSupplied
  - errors.consolidatedPartnershipsSupplied
  - errors.countryCodeLengthError
  - errors.countryCodeValueError
  - errors.deemedParentWrongDetailsSuppliedError
  - errors.deemedParentsEmpty
  - errors.endDateAfterStartDate
  - errors.expenseAndIncomeBothNotGreaterThanZero
  - errors.groupCompanyDetailsTotalCompaniesError
  - errors.groupEBITDANotSupplied
  - errors.groupEBITDASupplied
  - errors.groupRatioBlendedNotElectedError
  - errors.groupRatioBlendedNotSupplied
  - errors.groupRatioBlendedSupplied
  - errors.investorGroupsEmpty
  - errors.maxThreeDeemedParents
  - errors.minTwoDeemedParents
  - errors.negativeAngieError
  - errors.netTaxInterestExpenseDecimalError
  - errors.netTaxInterestExpenseError
  - errors.netTaxInterestIncomeDecimalError
  - errors.netTaxInterestIncomeError
  - errors.noTotalNetTaxInterestIncomeDuringRestriction
  - errors.nonConsolidatedInvestmentNameCharacterError
  - errors.nonConsolidatedInvestmentNameLengthError
  - errors.nonConsolidatedInvestmentNotSupplied
  - errors.nonConsolidatedInvestmentSupplied
  - errors.nonConsolidatedInvestmentEmpty
  - errors.parentCompanyCanNotBeUltimateAndDeemed
  - errors.parentCompanyDetailsNotSupplied
  - errors.parentCompanyDetailsSupplied
  - errors.reportingCompanyNotAppointed
  - errors.restrictionNotGreaterThanExpense
  - errors.revisedReturnDetailsCharacterError
  - errors.revisedReturnDetailsLengthError
  - errors.revisedReturnDetailsNotSupplied
  - errors.revisedReturnDetailsSupplied
  - errors.startDateCannotBeBeforeMinimum
  - errors.startDateCannotBeInFuture
  - errors.taxEBITDADecimalError
  - errors.uTRChecksumError
  - errors.uTRLengthError
  - errors.ukCompaniesEmpty
  - errors.ultimateParentWrongDetailsSuppliedError
  - errors.wrongDeemedParentIsUKCompanyAndNonUK
  - errors.wrongDeemedParentIsUkCompanyAndPartnership
  - errors.wrongDeemedParentIsUkPartnershipAndNonUKCompany
  - errors.wrongUltimateParentIsUKCompanyAndNonUK
  - errors.wrongUltimateParentIsUkCompanyAndPartnership
  - errors.wrongUltimateParentIsUkPartnershipAndNonUKCompany
displayName: Abbreviated Return
description: Request to submit an Abbreviated return for an Interest Restriction Return
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/abbreviatedReturnSchema.json
    examples:
      example-1:
        description: Abbreviated Return
        value: !include examples/return/abbreviatedReturn/request.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/abbreviatedReturnResponseSchema.json
        examples:
          example-1:
            description: Typical response received
            value: !include examples/return/abbreviatedReturn/response.json
