is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
displayName: Validate an Abbreviated Interest Restriction Return
description: Validates the payload for an Abbreviated Interest Restriction Return without submitting the return
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/abbreviatedReturnSchema.json
    examples:
      example-1:
        description: Abbreviated Return
        value: !include examples/return/abbreviatedReturn/request.json
responses:
  204: