#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Matching resource not found.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  downstreamError:
    responses:
      500:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: An internal server error occurred.
              value:
                code: INTERNAL_SERVER_ERROR
  badRequest:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Invalid request.
              value:
                code: INVALID_REQUEST
  invalidBodyType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Expecting text/json or application/json body.
              value:
                code: INVALID_BODY_TYPE
  unauthorised:
    responses:
      401:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The client and/or agent is not authorised.
              value:
                code: CLIENT_OR_AGENT_NOT_AUTHORISED    
  invalidAcceptHeader:
    responses:
      406:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The accept header is missing or invalid.
              value:
                code: ACCEPT_HEADER_INVALID   
  unsupportedVersion:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The requested resource could not be found.
              value:
                code: NOT_FOUND       
  cannotBeUkAndNonUk:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Identity of company submitting cannot contain data for UK and NonUK field
              value:
                code: INVALID_REQUEST          
  qngieDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: qngie has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  groupEBITDADecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: groupEBITDA has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  groupRatioDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: groupRatio has greater than the allowed 5 decimal places.
              value:
                code: INVALID_REQUEST
  groupRatioError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio must be between 0 and 100%
              value:
                code: INVALID_REQUEST
  groupRatioCalculationError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'The value for Group Ratio Percent you provided [GROUP RATIO], does not match the value calculated from the provided QNGIE ([QNGIE]) and group-EBITDA [GROUP EBITDA], [CALCULATED GROUP RATIO]'
              value:
                code: INVALID_REQUEST
  negativeOrZeroGroupEBITDAError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: If group-EBITDA is negative or zero, groupRatio must be set to 100
              value:
                code: INVALID_REQUEST
  negativeOrZeroGroupRatioError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: If group ratio calculation is negative then group ratio should be 100%
              value:
                code: INVALID_REQUEST
  allocatedReactivationsCannotBeNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: currentPeriodReactivation cannot be negative
              value:
                code: INVALID_REQUEST
  allocatedReactivationsDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: currentPeriodReactivation is only allowed to be two decimal place
              value:
                code: INVALID_REQUEST
  reportingCompanyNotAppointed:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: You need to appoint a reporting company
              value:
                code: INVALID_REQUEST
  revisedReturnDetailsNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A description of the amendments made to the return must be supplied if this is a revised return
              value:
                code: INVALID_REQUEST
  revisedReturnDetailsSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A description of the amendments made to the return cannot be supplied if this is an original return
              value:
                code: INVALID_REQUEST
  negativeAngieError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ANGIE cannot be negative
              value:
                code: INVALID_REQUEST
  angieDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ANGIE has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  groupLevelInterestRestrictionsAndReactivationSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: You cannot supply both a group level restriction and reactivation in the same return
              value:
                code: INVALID_REQUEST
  interestReactivationCapNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Interest Reactivation Cap is required if the group is subject to interest reactivation
              value:
                code: INVALID_REQUEST
  totalReactivationsDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalReactivation has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  totalReactivationsDoesNotMatch:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'Calculated reactivations is [CALCULATED AMOUNT] which does not match the supplied amount of [TOTAL REACTIVATIONS]'
              value:
                code: INVALID_REQUEST
  totalReactivationsNotGreaterThanCapacity:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'Calculated Total Reactivations: [CALCULATED AMOUNT] cannot not be greater than Reactivations Capacity: [INTEREST REACTIVATION CAPACITY]'
              value:
                code: INVALID_REQUEST
  totalRestrictionsDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalRestrictions has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  totalRestrictionsDoesNotMatch:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'Calculated restrictions is [CALCULATED AMOUNT] which does not match the supplied amount of [TOTAL RESTRICTIONS]'
              value:
                code: INVALID_REQUEST
  aggInterestPositiveAndRestriction:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'You cannot have a calculated totalTaxInterest: [TOTAL TAX INTEREST] when there the  full return is subjectToRestriction: [SUBJECT TO RESTRICTION]'
              value:
                code: INVALID_REQUEST
  missingAllocatedRestrictionsForCompanies:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Allocated Restrictions must be supplied for this UK Company when the group is subject to Interest Restriction
              value:
                code: INVALID_REQUEST
  companiesContainedAllocatedRestrictions:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Allocated Restrictions cannot be supplied for this UK Company when the group is not subject to Interest Restriction
              value:
                code: INVALID_REQUEST
  missingAllocatedReactivationsForCompanies:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Allocated Reactivations must be supplied for this UK Company when the group is subject to Interest Reactivation
              value:
                code: INVALID_REQUEST
  companiesContainedAllocatedReactivations:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Allocated Reactivations cannot be supplied for this UK Company when the group is not subject to Interest Reactivation
              value:
                code: INVALID_REQUEST
  adjustedNetGroupInterestNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Adjusted Group Interest is required when Group Ratio is elected
              value:
                code: INVALID_REQUEST
  adjustedNetGroupInterestSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Adjusted Group Interest should not be supplied as Group Ratio is not elected
              value:
                code: INVALID_REQUEST
  netTaxInterestExpenseError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The supplied Net Tax Interest Expense is Negative, which it can not be.
              value:
                code: INVALID_REQUEST
  netTaxInterestExpenseDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The supplied Net Tax Interest Expense has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  netTaxInterestIncomeError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The supplied Net Tax Interest Income is Negative, which it can not be.
              value:
                code: INVALID_REQUEST
  netTaxInterestIncomeDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The supplied Net Tax Interest Income has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  expenseAndIncomeBothNotGreaterThanZero:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A company can not have both a net tax interest expense and a net tax interest income
              value:
                code: INVALID_REQUEST
  restrictionNotGreaterThanExpense:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A company can not have a allocated restriction greater than its net tax expense
              value:
                code: INVALID_REQUEST
  noTotalNetTaxInterestIncomeDuringRestriction:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: You cannot have a Net Tax Interest Income when you apply a restriction
              value:
                code: INVALID_REQUEST
  taxEBITDADecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The supplied Tax EBITDA has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  allocatedRestrictionNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: disallowanceAp[INDEX] must have a value when ap[INDEX]End is supplied
              value:
                code: INVALID_REQUEST
  allocatedRestrictionSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: disallowanceAp[INDEX] cannot have a value when no ap[INDEX]End is supplied
              value:
                code: INVALID_REQUEST
  allocatedRestrictionLaterPeriodSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ap[INDEX]End cannot be supplied as a previous period is missing
              value:
                code: INVALID_REQUEST
  allocatedRestrictionNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: disallowanceAp[INDEX] cannot be negative
              value:
                code: INVALID_REQUEST
  allocatedRestrictionDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: disallowanceAp[INDEX] has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  allocatedRestrictionTotalNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalDisallowances must be supplied if restrictions are supplied
              value:
                code: INVALID_REQUEST
  allocatedRestrictionTotalNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalDisallowances cannot be negative
              value:
                code: INVALID_REQUEST
  allocatedRestrictionTotalDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalDisallowances has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  allocatedRestrictionTotalDoesNotMatch:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The totalDisallowances was [CALCULATED AMOUNT] which does not match the supplied amount of [TOTAL DISALLOWANCES]
              value:
                code: INVALID_REQUEST
  allocatedRestrictionDateBeforePrevious:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ap[INDEX]End cannot be equal to or before ap[INDEX - 1]EndDate
              value:
                code: INVALID_REQUEST
  ap1NotAfterGroupStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ap1EndDate ([AP1 END DATE]) must be after the group accounting period start date ([GROUP START DATE])
              value:
                code: INVALID_REQUEST
  ap3BeforeGroupEndDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ap3EndDate ([AP3 END DATE]) is before the group accounting period end date ([GROUP END DATE])
              value:
                code: INVALID_REQUEST
  interestAllowanceForPeriodCannotBeNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestAllowanceForPeriod cannot be negative
              value:
                code: INVALID_REQUEST

  interestAllowanceBroughtForwardCannotBeNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestAllowanceBroughtForward cannot be negative
              value:
                code: INVALID_REQUEST

  interestCapacityForPeriodCannotBeNegative:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestCapacityForPeriod cannot be negative
              value:
                code: INVALID_REQUEST
  interestAllowanceForPeriodDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestAllowanceForPeriod has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  interestAllowanceBroughtForwardDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestAllowanceBroughtForward has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  interestCapacityForPeriodDecimalError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: interestCapacityForPeriod has greater than the allowed 2 decimal places.
              value:
                code: INVALID_REQUEST
  countryCodeValueError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Country code [COUNTRY CODE] is not a valid country code
              value:
                code: INVALID_REQUEST
  countryCodeLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: UTR is [LENGTH] characters long and should be 2
              value:
                code: INVALID_REQUEST
  consolidatedPartnershipsSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Consolidated Partnership is not elected, unable to supply partnership name
              value:
                code: INVALID_REQUEST
  consolidatedPartnershipsNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Consolidated Partnership is elected, must supply partnership name
              value:
                code: INVALID_REQUEST
  consolidatedPartnershipsEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: consolidatedPartnership must have at least 1 partnership
              value:
                code: INVALID_REQUEST
  identityOfAppointingCompanyIsNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Identity of Appointing Company must be supplied if it is not the same as the reporting company or agent
              value:
                code: INVALID_REQUEST
  identityOfAppointingCompanyIsSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Identity of Appointing Company must not be supplied if it is the same as the reporting company or agent
              value:
                code: INVALID_REQUEST
  ultimateParentCompanyIsSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Ultimate Parent Company must not be supplied if it is the same as the reporting company
              value:
                code: INVALID_REQUEST
  authorisingCompaniesEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: authorisingCompanies must have at least 1 authorising company
              value:
                code: INVALID_REQUEST
  parentCompanyCanNotBeUltimateAndDeemed:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Parent Company Model cannot contain data for Ultimate and Deemed field
              value:
                code: INVALID_REQUEST
  deemedParentsEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: deemedParent must have at least 1 deemed parent if supplied
              value:
                code: INVALID_REQUEST
  minTwoDeemedParents:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Min number of deemed Parent can only be two
              value:
                code: INVALID_REQUEST
  maxThreeDeemedParents:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Max number of deemed Parents can only be three
              value:
                code: INVALID_REQUEST
  ultimateParentWrongDetailsSuppliedError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given the details for all three ultimate parents please give correct detail
              value:
                code: INVALID_REQUEST
  wrongUltimateParentIsUkCompanyAndPartnership:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK Company and Partnership
              value:
                code: INVALID_REQUEST
  wrongUltimateParentIsUkPartnershipAndNonUKCompany:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK Partnership and NonUK Company
              value:
                code: INVALID_REQUEST
  wrongUltimateParentIsUKCompanyAndNonUK:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK and Non UK Company
              value:
                code: INVALID_REQUEST
  nonConsolidatedInvestmentNameLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Investment name is [LENGTH] characters long and should be between 1 and 5000 character
              value:
                code: INVALID_REQUEST
  nonConsolidatedInvestmentNameCharacterError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Investment name contains invalid character
              value:
                code: INVALID_REQUEST
  deemedParentWrongDetailsSuppliedError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given the details for all three ultimate parents please give correct detail
              value:
                code: INVALID_REQUEST
  wrongDeemedParentIsUkCompanyAndPartnership:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK Company and Partnership
              value:
                code: INVALID_REQUEST
  wrongDeemedParentIsUkPartnershipAndNonUKCompany:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK Partnership and NonUK Company
              value:
                code: INVALID_REQUEST
  wrongDeemedParentIsUKCompanyAndNonUK:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: you have given details for a UK and Non UK Company
              value:
                code: INVALID_REQUEST
  groupRatioBlendedSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio is not elected, unable to elect GroupRatioBlended Election
              value:
                code: INVALID_REQUEST
  groupRatioBlendedNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio is elected, must supply GroupRatioBlended Election
              value:
                code: INVALID_REQUEST
  groupEBITDASupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio is not elected, unable to elect groupEBITDAChargeableGains Election
              value:
                code: INVALID_REQUEST
  groupEBITDANotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio is elected, must provide groupEBITDAChargeableGains Election
              value:
                code: INVALID_REQUEST
  uTRChecksumError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: UTR Check Sum does not satisfy the check sum
              value:
                code: INVALID_REQUEST
  uTRLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: UTR is [LENGTH] characters long and should be 10
              value:
                code: INVALID_REQUEST
  startDateCannotBeInFuture:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Start date cannot be in the future
              value:
                code: INVALID_REQUEST
  startDateCannotBeBeforeMinimum:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Start date cannot be before 2016-10-01
              value:
                code: INVALID_REQUEST
  endDateAfterStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: End Date must be after start date
              value:
                code: INVALID_REQUEST
  accountingPeriod18MonthsMax:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The end date must be less than 18 months after the start date
              value:
                code: ACCOUNTING_PERIOD_MAX
  parentCompanyDetailsNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Parent Company is required if the Reporting Company is not the same as the Ultimate Parent
              value:
                code: INVALID_REQUEST
  parentCompanyDetailsSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Parent Company should not be supplied as the parent is the same as the Reporting Company
              value:
                code: INVALID_REQUEST
  ukCompaniesEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: ukCompanies must have at least 1 UK company
              value:
                code: INVALID_REQUEST
  companyMakingAppointmentMustSupplyDetails:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: companyMakingRevocation must be supplied when isReportingCompanyRevokingItself is false
              value:
                code: INVALID_REQUEST
  declaredFiftyPercentOfEligibleCompanies:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The declaration that the listed companies constitute at least 50% of the eligible companies must be true
              value:
                code: INVALID_REQUEST
  detailsNotNeededIfCompanyRevokingItself:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: If the reporting company is submitting this revocation, the identity of company making revocation is not needed.
              value:
                code: INVALID_REQUEST
  ultimateParentCompanyIsSuppliedRevoke:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Ultimate Parent Company must not be supplied if it is the same as the reporting company
              value:
                code: INVALID_REQUEST
  groupCompanyDetailsTotalCompaniesError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: totalCompanies is [TOTAL COMPANIES] but it must be greater than 0 and less than 32767
              value:
                code: INVALID_REQUEST
  revisedReturnDetailsLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The revised return details are [LENGTH] characters long and should be between 1 and 5000 character
              value:
                code: INVALID_REQUEST
  revisedReturnDetailsCharacterError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The revised return details contain invalid character
              value:
                code: INVALID_REQUEST
  companyNameLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Company name is [LENGTH] characters long and should be between 1 and 160
              value:
                code: INVALID_REQUEST
  companyNameCharactersError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Company name contains invalid characters.
              value:
                code: INVALID_REQUEST
  groupRatioBlendedNotElectedError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Group Ratio Blended is not elected, unable to supply investor group
              value:
                code: INVALID_REQUEST
  investorGroupsEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: investorGroups must have at least 1 investor if supplied
              value:
                code: INVALID_REQUEST
  agentNameLengthError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Agent name must be between 1-160 characters if supplied
              value:
                code: INVALID_REQUEST
  agentNameNotSuppliedError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Agent name must be supplied if agent is acting on behalf of company
              value:
                code: INVALID_REQUEST
  agentNameSuppliedError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Agent name must not be supplied if agent is not acting on behalf of company
              value:
                code: INVALID_REQUEST
  agentNameCharactersError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Agent name contains invalid characters.
              value:
                code: INVALID_REQUEST
  nonConsolidatedInvestmentSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: You can only provide non-consolidated investments if non-consolidated election is made
              value:
                code: INVALID_REQUEST
  nonConsolidatedInvestmentNotSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: You must provide non-consolidated investments if non-consolidated election is made
              value:
                code: INVALID_REQUEST
  nonConsolidatedInvestmentEmpty:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: nonConsolidatedInvestments must contain at least 1 value if supplied
              value:
                code: INVALID_REQUEST
