#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: Matching resource not found.
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO is not valid
                value:
                  code: FORMAT_NINO
  downstreamError:
    responses:
      500:
        body:
          application/json:
            type: types.errorResponse
            examples:
              downstreamError:
                description: An internal server error occurred.
                value:
                  code: INTERNAL_SERVER_ERROR
  badRequest:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              badRequest:
                description: Invalid request.
                value:
                  code: INVALID_REQUEST
  invalidBodyType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidBodyType:
                description: Expecting text/json or application/json body.
                value:
                  code: INVALID_BODY_TYPE
  unauthorised:
    responses:
      401:
        body:
          application/json:
            type: types.errorResponse
            examples:
              unauthorised:
                description: The client and/or agent is not authorised.
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED   
  invalidAcceptHeader:
    responses:
      406:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidAcceptHeader:
                description: The accept header is missing or invalid.
                value:
                  code: ACCEPT_HEADER_INVALID   
  unsupportedVersion:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              unsupportedVersion:
                description: The requested resource could not be found.
                value:
                  code: NOT_FOUND
  forbiddenIndividuals:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              unsupportedVersion:
                description: You are unable to access this service as an individual. This service is only available to individual companies or groups of companies.
                value:
                  code: FORBIDDEN