is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.downstreamError
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
  - errors.accountingPeriod18MonthsMax
  - errors.adjustedNetGroupInterestNotSupplied
  - errors.adjustedNetGroupInterestSupplied
  - errors.agentNameCharactersError
  - errors.agentNameLengthError
  - errors.agentNameNotSuppliedError
  - errors.agentNameSuppliedError
  - errors.aggInterestPositiveAndRestriction
  - errors.allocatedReactivationsCannotBeNegative
  - errors.allocatedReactivationsDecimalError
  - errors.allocatedRestrictionDateBeforePrevious
  - errors.allocatedRestrictionDecimalError
  - errors.allocatedRestrictionLaterPeriodSupplied
  - errors.allocatedRestrictionNegative
  - errors.allocatedRestrictionNotSupplied
  - errors.allocatedRestrictionSupplied
  - errors.allocatedRestrictionTotalDecimalError
  - errors.allocatedRestrictionTotalDoesNotMatch
  - errors.allocatedRestrictionTotalNegative
  - errors.allocatedRestrictionTotalNotSupplied
  - errors.angieDecimalError
  - errors.ap1NotAfterGroupStartDate
  - errors.ap3BeforeGroupEndDate
  - errors.companiesContainedAllocatedReactivations
  - errors.companiesContainedAllocatedRestrictions
  - errors.companyNameCharactersError
  - errors.companyNameLengthError
  - errors.consolidatedPartnershipsEmpty
  - errors.consolidatedPartnershipsNotSupplied
  - errors.consolidatedPartnershipsSupplied
  - errors.countryCodeLengthError
  - errors.countryCodeValueError
  - errors.deemedParentWrongDetailsSuppliedError
  - errors.deemedParentsEmpty
  - errors.endDateAfterStartDate
  - errors.expenseAndIncomeBothNotGreaterThanZero
  - errors.groupCompanyDetailsTotalCompaniesError
  - errors.groupEBITDADecimalError
  - errors.groupEBITDANotSupplied
  - errors.groupEBITDASupplied
  - errors.interestAllowanceForPeriodCannotBeNegative
  - errors.interestAllowanceBroughtForwardCannotBeNegative
  - errors.interestCapacityForPeriodCannotBeNegative
  - errors.interestAllowanceForPeriodDecimalError
  - errors.interestAllowanceBroughtForwardDecimalError
  - errors.interestCapacityForPeriodDecimalError
  - errors.groupLevelInterestRestrictionsAndReactivationSupplied
  - errors.groupRatioBlendedNotElectedError
  - errors.groupRatioBlendedNotSupplied
  - errors.groupRatioBlendedSupplied
  - errors.groupRatioCalculationError
  - errors.groupRatioDecimalError
  - errors.groupRatioError
  - errors.interestReactivationCapNotSupplied
  - errors.investorGroupsEmpty
  - errors.maxThreeDeemedParents
  - errors.minTwoDeemedParents
  - errors.missingAllocatedReactivationsForCompanies
  - errors.missingAllocatedRestrictionsForCompanies
  - errors.negativeAngieError
  - errors.negativeOrZeroGroupEBITDAError
  - errors.negativeOrZeroGroupRatioError
  - errors.netTaxInterestExpenseDecimalError
  - errors.netTaxInterestExpenseError
  - errors.netTaxInterestIncomeDecimalError
  - errors.netTaxInterestIncomeError
  - errors.noTotalNetTaxInterestIncomeDuringRestriction
  - errors.nonConsolidatedInvestmentNameCharacterError
  - errors.nonConsolidatedInvestmentNameLengthError
  - errors.nonConsolidatedInvestmentNotSupplied
  - errors.nonConsolidatedInvestmentSupplied
  - errors.nonConsolidatedInvestmentEmpty
  - errors.parentCompanyCanNotBeUltimateAndDeemed
  - errors.parentCompanyDetailsNotSupplied
  - errors.parentCompanyDetailsSupplied
  - errors.qngieDecimalError
  - errors.reportingCompanyNotAppointed
  - errors.restrictionNotGreaterThanExpense
  - errors.revisedReturnDetailsCharacterError
  - errors.revisedReturnDetailsLengthError
  - errors.revisedReturnDetailsNotSupplied
  - errors.revisedReturnDetailsSupplied
  - errors.startDateCannotBeBeforeMinimum
  - errors.startDateCannotBeInFuture
  - errors.taxEBITDADecimalError
  - errors.totalReactivationsDecimalError
  - errors.totalReactivationsDoesNotMatch
  - errors.totalReactivationsNotGreaterThanCapacity
  - errors.totalRestrictionsDecimalError
  - errors.totalRestrictionsDoesNotMatch
  - errors.uTRChecksumError
  - errors.uTRLengthError
  - errors.ukCompaniesEmpty
  - errors.ultimateParentWrongDetailsSuppliedError
  - errors.wrongDeemedParentIsUKCompanyAndNonUK
  - errors.wrongDeemedParentIsUkCompanyAndPartnership
  - errors.wrongDeemedParentIsUkPartnershipAndNonUKCompany
  - errors.wrongUltimateParentIsUKCompanyAndNonUK
  - errors.wrongUltimateParentIsUkCompanyAndPartnership
  - errors.wrongUltimateParentIsUkPartnershipAndNonUKCompany
displayName: Post a Full Interest Restriction Return
description: To submit a Full IRR
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/fullReturnSchema.json
    examples:
      example-1:
        description: Submit a full IRR
        value: !include examples/return/full/request.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/fullReturnResponseSchema.json
        examples:
          example-1:
            description: Typical response received
            value: !include examples/return/full/response.json
