is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
  - errors.forbiddenIndividuals
displayName: Validate a Full Interest Restriction Return
description: Validates the payload for a Full Interest Restriction Return without submitting the return
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/fullReturnSchema.json
    examples:
      example-1:
        description: Validate a full IRR
        value: !include examples/return/full/request.json
responses:
  204: