is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
displayName: Validate Revoking a Reporting Company
description: Validates the payload for Revoking a Reporting Company without submitting the Revoke request
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/revokeReportingCompanySchema.json
    examples:
      example-1:
        description: Revoke Reporting Company
        value: !include examples/reportingCompany/revoke/request.json
responses:
  204:
