is:
  - headers.acceptJson
  - headers.contentTypeJson
  - errors.notFound
  - errors.downstreamError
  - errors.badRequest
  - errors.invalidBodyType
  - errors.unauthorised
  - errors.invalidAcceptHeader
  - errors.unsupportedVersion
  - errors.headers.acceptJson
displayName: Revoke a Reporting Company
description: Request to revoke a Reporting Company that can submit Interest Restriction Returns
(annotations.scope): "write:interest-restriction-return"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:interest-restriction-return" ] } ]
body:
  application/json:
    description: The payload required for the post to be successful
    type: !include schemas/revokeReportingCompanySchema.json
    examples:
      example-1:
        description: Revoke Reporting Company
        value: !include examples/reportingCompany/revoke/request.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/revokeReportingCompanyResponseSchema.json
        examples:
          example-1:
            description: Typical response received
            value: !include examples/reportingCompany/revoke/response.json
